// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repository;

#nullable disable

namespace CardGame.Migrations
{
    [DbContext(typeof(RepoContext))]
    partial class RepoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Domain.Card", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Suit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Number = "Ace",
                            Suit = "Hearts"
                        },
                        new
                        {
                            Id = 2,
                            Number = "Two",
                            Suit = "Hearts"
                        },
                        new
                        {
                            Id = 3,
                            Number = "Three",
                            Suit = "Hearts"
                        },
                        new
                        {
                            Id = 4,
                            Number = "Four",
                            Suit = "Hearts"
                        },
                        new
                        {
                            Id = 5,
                            Number = "Five",
                            Suit = "Hearts"
                        },
                        new
                        {
                            Id = 6,
                            Number = "Six",
                            Suit = "Hearts"
                        },
                        new
                        {
                            Id = 7,
                            Number = "Seven",
                            Suit = "Hearts"
                        },
                        new
                        {
                            Id = 8,
                            Number = "Eight",
                            Suit = "Hearts"
                        },
                        new
                        {
                            Id = 9,
                            Number = "Nine",
                            Suit = "Hearts"
                        },
                        new
                        {
                            Id = 10,
                            Number = "Ten",
                            Suit = "Hearts"
                        },
                        new
                        {
                            Id = 11,
                            Number = "Jack",
                            Suit = "Hearts"
                        },
                        new
                        {
                            Id = 12,
                            Number = "Queen",
                            Suit = "Hearts"
                        },
                        new
                        {
                            Id = 13,
                            Number = "King",
                            Suit = "Hearts"
                        },
                        new
                        {
                            Id = 14,
                            Number = "Ace",
                            Suit = "Diamonds"
                        },
                        new
                        {
                            Id = 15,
                            Number = "Two",
                            Suit = "Diamonds"
                        },
                        new
                        {
                            Id = 16,
                            Number = "Three",
                            Suit = "Diamonds"
                        },
                        new
                        {
                            Id = 17,
                            Number = "Four",
                            Suit = "Diamonds"
                        },
                        new
                        {
                            Id = 18,
                            Number = "Five",
                            Suit = "Diamonds"
                        },
                        new
                        {
                            Id = 19,
                            Number = "Six",
                            Suit = "Diamonds"
                        },
                        new
                        {
                            Id = 20,
                            Number = "Seven",
                            Suit = "Diamonds"
                        },
                        new
                        {
                            Id = 21,
                            Number = "Eight",
                            Suit = "Diamonds"
                        },
                        new
                        {
                            Id = 22,
                            Number = "Nine",
                            Suit = "Diamonds"
                        },
                        new
                        {
                            Id = 23,
                            Number = "Ten",
                            Suit = "Diamonds"
                        },
                        new
                        {
                            Id = 24,
                            Number = "Jack",
                            Suit = "Diamonds"
                        },
                        new
                        {
                            Id = 25,
                            Number = "Queen",
                            Suit = "Diamonds"
                        },
                        new
                        {
                            Id = 26,
                            Number = "King",
                            Suit = "Diamonds"
                        },
                        new
                        {
                            Id = 27,
                            Number = "Ace",
                            Suit = "Spades"
                        },
                        new
                        {
                            Id = 28,
                            Number = "Two",
                            Suit = "Spades"
                        },
                        new
                        {
                            Id = 29,
                            Number = "Three",
                            Suit = "Spades"
                        },
                        new
                        {
                            Id = 30,
                            Number = "Four",
                            Suit = "Spades"
                        },
                        new
                        {
                            Id = 31,
                            Number = "Five",
                            Suit = "Spades"
                        },
                        new
                        {
                            Id = 32,
                            Number = "Six",
                            Suit = "Spades"
                        },
                        new
                        {
                            Id = 33,
                            Number = "Seven",
                            Suit = "Spades"
                        },
                        new
                        {
                            Id = 34,
                            Number = "Eight",
                            Suit = "Spades"
                        },
                        new
                        {
                            Id = 35,
                            Number = "Nine",
                            Suit = "Spades"
                        },
                        new
                        {
                            Id = 36,
                            Number = "Ten",
                            Suit = "Spades"
                        },
                        new
                        {
                            Id = 37,
                            Number = "Jack",
                            Suit = "Spades"
                        },
                        new
                        {
                            Id = 38,
                            Number = "Queen",
                            Suit = "Spades"
                        },
                        new
                        {
                            Id = 39,
                            Number = "King",
                            Suit = "Spades"
                        },
                        new
                        {
                            Id = 40,
                            Number = "Ace",
                            Suit = "Clubs"
                        },
                        new
                        {
                            Id = 41,
                            Number = "Two",
                            Suit = "Clubs"
                        },
                        new
                        {
                            Id = 42,
                            Number = "Three",
                            Suit = "Clubs"
                        },
                        new
                        {
                            Id = 43,
                            Number = "Four",
                            Suit = "Clubs"
                        },
                        new
                        {
                            Id = 44,
                            Number = "Five",
                            Suit = "Clubs"
                        },
                        new
                        {
                            Id = 45,
                            Number = "Six",
                            Suit = "Clubs"
                        },
                        new
                        {
                            Id = 46,
                            Number = "Seven",
                            Suit = "Clubs"
                        },
                        new
                        {
                            Id = 47,
                            Number = "Eight",
                            Suit = "Clubs"
                        },
                        new
                        {
                            Id = 48,
                            Number = "Nine",
                            Suit = "Clubs"
                        },
                        new
                        {
                            Id = 49,
                            Number = "Ten",
                            Suit = "Clubs"
                        },
                        new
                        {
                            Id = 50,
                            Number = "Jack",
                            Suit = "Clubs"
                        },
                        new
                        {
                            Id = 51,
                            Number = "Queen",
                            Suit = "Clubs"
                        },
                        new
                        {
                            Id = 52,
                            Number = "King",
                            Suit = "Clubs"
                        });
                });

            modelBuilder.Entity("Domain.CardHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CardId")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.HasIndex("PlayerId");

                    b.ToTable("CardHistories");
                });

            modelBuilder.Entity("Domain.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("Domain.CardHistory", b =>
                {
                    b.HasOne("Domain.Card", "Card")
                        .WithMany()
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");

                    b.Navigation("Player");
                });
#pragma warning restore 612, 618
        }
    }
}
